spring:
  cloud:
    config:
      server:
        git:
          uri: file://app/configuration-repo
          clone-on-start: true

eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery-server:8761/eureka