spring:
  cloud:
    config:
      server:
        git:
          uri: "file://${user.home}/configuration-repo"
          clone-on-start: true
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka