spring:
  application:
    name: CONFIGURATION-SERVER
  cloud:
    config:
      server:
        git:
          uri: file://${user.home}/configuration-repo
          clone-on-start: true
server:
  port: 8888

eureka:
  instance:
    prefer-ip-address: true

