spring:
  profiles:
    active: native
  application:
    name: CONFIGURATION-SERVER
  cloud:
    config:
      server:
        git:
          uri: file://app/config
          clone-on-start: true
server:
  port: 8888

eureka:
  instance:
    prefer-ip-address: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl.defaultZone: http://discovery-server:8761/eureka
